name: IA Daily Value Digest
on:
  schedule:
    - cron: "30 11 * * *"   # roda todo dia 8h30 Recife (UTC-3)
  workflow_dispatch: {}     # permite rodar manualmente pelo botão “Run workflow”

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m src.main
      - name: Upload daily report
        uses: actions/upload-artifact@v4
        with:
          name: digest
          path: out/
